"""
Rectified Flow Reflow — Liu et al. 2022, arXiv:2209.14577 §3.

See THEORY_NOTES.md §6 for mathematical derivation.

Core idea
---------
A trained FM model's learned paths are curved in practice (it averages many
straight trajectories across the data distribution).  Reflow straightens them:

  Step 1 (OFFLINE — run scripts/generate_reflow_pairs.py first):
    z_1 ~ N(0,I)
    x_0_hat = FM.euler(z_1, NFE=50)          [full FM inference]
    save (z_1, x_0_hat) pairs to disk

  Step 2 (THIS FILE — standard FM training on straight pairs):
    x_t = (1-t)·x_0_hat + t·z_1             [interpolate the SAME pair]
    v   = z_1 - x_0_hat                      [constant velocity]
    loss = MSE(v_θ(x_t, t), v)

Because z_1 and x_0_hat are now paired (not random), the ODE path is
straighter, and fewer Euler steps are needed at inference.

algorithm_kwargs
----------------
    pairs_path (str, required):
        Path to .pt file containing {"z1": Tensor(N,C,H,W), "x0": Tensor(N,C,H,W)}
        generated by scripts/generate_reflow_pairs.py.

IMPORTANT: generate_reflow_pairs.py must be run before training this algorithm.
See IMPLEMENTATION_LOG.md §Phase 4 for the generation command.
"""

import os
from typing import Any, Dict

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

from algorithms.base import BaseAlgorithm


class ReflowAlgorithm(BaseAlgorithm):
    """
    Reflow: standard FM loss applied to pre-generated (z1, x0) pairs.
    Inference is identical to FlowMatchingAlgorithm (Euler ODE).

    The training data is loaded from a pre-generated .pt file.
    The real-image DataLoader passed by Trainer is NOT used here —
    we substitute the pairs dataset in training_step.
    """

    def __init__(self, model: nn.Module, algorithm_kwargs: Dict[str, Any] = None):
        super().__init__(model, algorithm_kwargs)

        pairs_path = self.algorithm_kwargs.get("pairs_path")
        if not pairs_path:
            raise ValueError(
                "ReflowAlgorithm requires algorithm_kwargs['pairs_path'] pointing "
                "to a .pt file generated by scripts/generate_reflow_pairs.py.\n"
                "Run: python scripts/generate_reflow_pairs.py --help"
            )
        if not os.path.exists(pairs_path):
            raise FileNotFoundError(
                f"Reflow pairs file not found: {pairs_path}\n"
                "Run scripts/generate_reflow_pairs.py first."
            )

        data = torch.load(pairs_path, map_location="cpu", weights_only=True)
        self._z1 = data["z1"]    # (N, C, H, W) noise
        self._x0 = data["x0"]    # (N, C, H, W) generated clean images
        self._pair_idx = 0       # simple sequential cursor (shuffled per epoch externally)
        self._n_pairs = self._z1.shape[0]

    # trainable_modules: only self.model (default from BaseAlgorithm)

    def training_step(self, batch: torch.Tensor) -> Dict[str, torch.Tensor]:
        """
        Standard FM loss on pre-generated straight pairs.
        `batch` (real images from DataLoader) is used only to infer
        batch size and device — the actual training data comes from pairs.
        """
        B   = batch.shape[0]
        dev = batch.device

        # Draw B pairs (with wrap-around)
        idx  = torch.randint(0, self._n_pairs, (B,))
        z1   = self._z1[idx].to(dev)    # noise endpoint
        x0   = self._x0[idx].to(dev)    # generated image endpoint

        # Standard FM on straight pair
        t      = torch.rand(B, device=dev)
        t_view = t.view(-1, 1, 1, 1)
        x_t    = (1.0 - t_view) * x0 + t_view * z1    # interpolate THIS pair
        v      = z1 - x0                               # constant velocity along pair

        pred_v = self.model(x_t, t)
        loss   = F.mse_loss(pred_v, v)
        return {"loss": loss}

    def sample(self, n_samples: int, nfe: int, device: torch.device) -> torch.Tensor:
        """Euler ODE integration — identical to FlowMatchingAlgorithm.sample()."""
        C   = self.model.cfg.in_channels
        H = W = self.model._expected_image_size
        x   = torch.randn(n_samples, C, H, W, device=device)
        step = 1.0 / nfe

        with torch.no_grad():
            for i in range(nfe):
                t_cur = 1.0 - i * step
                t_b   = torch.full((n_samples,), t_cur, device=device, dtype=torch.float32)
                v     = self.model(x, t_b)
                x     = x - v * step

        return x.clamp(-1.0, 1.0)
